[package]
name = "lancedb-example"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow-array = "43.0.0"
arrow-schema = "43.0.0"
lance = "0.7.3"
tokio = { version = "1", features = ["full"] }
vectordb = "0.2.5"
futures = "0.3"
